# Generated by Django 4.0.1 on 2022-01-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto_name', models.CharField(editable=False, max_length=32, verbose_name='Name')),
                ('usd_rate', models.DecimalField(decimal_places=4, editable=False, max_digits=16)),
                ('pln_rate', models.DecimalField(decimal_places=4, editable=False, max_digits=16)),
                ('date', models.DateTimeField(editable=False, verbose_name='Update date')),
            ],
        ),
    ]
